#! /bin/sh

## Script pós instalação Arch Linux

att() {
    pacman-optimize
    pacman -Syyu --noconfirm
    return 0
}

basic() {

    pacman -S xorg-server xorg-xinit xorg-apps gvfs-mtp xf86-video-intel alsa-utils pulseaudio pavucontrol alsa-oss alsa-lib libx264 --noconfirm
	if [ $?  -eq "0" ]; then
		echo 'Xorg, drivers de video, alsa e pulseaudio instalados'
        sleep 5
        interface
   	else
       	echo ERRO
       	exit 1
   	fi
}

interface() {

	pacman -S openbox oblogout thunar thunar-volman lxappearance lightdm lightdm-gtk-greeter arc-icon-theme bc xcompmgr nitrogen screenfetch git plank --noconfirm
	if [ $? -eq "0" ]; then
		echo 'Interface gráfica instalada'
        sleep 5
        fonts
   	else
       	echo ERRO
       	exit 1
   	fi

}

fonts() {

	pacman -S ttf-anonymous-pro ttf-bitstream-vera ttf-dejavu ttf-droid ttf-gentium ttf-liberation ttf-ubuntu-font-family --noconfirm
	if [ $? -eq "0" ]; then
   		echo 'Fontes instaladas'
        sleep 5
        programs
	else
    	echo ERRO
    	exit 1
	fi
}

programs() {

	pacman -S mousepad evince atom geogebra pycharm freemind firefox libreoffice-still vim conky terminator zsh --noconfirm
	if [ $? -eq "0" ]; then
		echo 'Programas instalados'
		sleep 5
		clean
    else
        echo ERRO
        exit 1
    fi
}

clean() {

	pacman -Scc --noconfirm
	if [ $? -eq "0" ]; then
	    pacman -Rns $(pacman -Qtdq) --noconfirm

        if [ $?  -eq "0" ]; then
            echo 'Cache e pacotes orfãos removidos'
        	confsys
		else
			echo 'Cache limpo'
			confsys
       	fi

    else
       	echo ERRO
       	exit 1
  	fi
}

confsys() {

    	pacman -Qq lightdm && systemctl enable lightdm

    	echo -e '[archlinuxfr]\nSigLevel = Never\nServer = http://repo.archlinux.fr/$arch' >> /etc/pacman.conf
    	pacman -Syy
}

if [ att ]; then
	basic
else
	echo 'Ocorreu um erro'
	exit 1
fi

sync
exit
