# .bash_aliases

if [ -x /usr/bin/dircolors ]; then
    eval "$(dircolors -b)"
fi

# LS ALIASES
alias ls="ls --color=auto"
alias ll="ls -l"
alias la="ls -A"
alias l="ls -CF"
alias dir="dir --color=auto"
alias vdir="vdir --color=auto"

# GREP ALIASES
alias grep="grep --color=auto"
alias fgrep="fgrep --color=auto"
alias egrep="egrep --color=auto"


